WITH TABLE_COUNT AS (
    SELECT C.HACKER_ID, H.NAME, COUNT(C.CHALLENGE_ID) AS NUM_CAL
    FROM HACKERS AS H
    INNER JOIN CHALLENGES AS C
    ON H.HACKER_ID = C.HACKER_ID
    GROUP BY C.HACKER_ID, H.NAME
)

SELECT HACKER_ID, NAME, NUM_CAL
FROM TABLE_COUNT
WHERE NUM_CAL = (
    SELECT MAX(NUM_CAL) FROM TABLE_COUNT
) 
OR NUM_CAL IN (
    SELECT NUM_CAL FROM TABLE_COUNT GROUP BY NUM_CAL HAVING COUNT(*) = 1
)
ORDER BY NUM_CAL DESC, HACKER_ID;
