SELECT H.HACKER_ID, H.NAME, SUM(MAX_SCORES.MAX_SCORE) AS TOTAL_SCORE
FROM HACKERS AS H
INNER JOIN (
    SELECT S.HACKER_ID, S.CHALLENGE_ID, MAX(S.SCORE) AS MAX_SCORE
    FROM SUBMISSIONS AS S
    GROUP BY S.HACKER_ID, S.CHALLENGE_ID
) AS MAX_SCORES
ON H.HACKER_ID = MAX_SCORES.HACKER_ID
GROUP BY H.HACKER_ID, H.NAME
HAVING TOTAL_SCORE > 0
ORDER BY TOTAL_SCORE DESC, H.HACKER_ID ASC;
