WITH CTE AS (
    SELECT COL.CONTEST_ID, CH.COLLEGE_ID, CH.CHALLENGE_ID 
    FROM CHALLENGES AS CH 
    JOIN COLLEGES AS COL 
    ON COL.COLLEGE_ID = CH.COLLEGE_ID
),

CTE2 AS (
    SELECT CTE.CONTEST_ID, 
           SUM(SS.TOTAL_SUBMISSIONS) AS TS, 
           SUM(SS.TOTAL_ACCEPTED_SUBMISSIONS) AS TAS 
    FROM CTE 
    JOIN SUBMISSION_STATS AS SS 
    ON SS.CHALLENGE_ID = CTE.CHALLENGE_ID 
    GROUP BY CTE.CONTEST_ID
),

CTE3 AS (
    SELECT CTE.CONTEST_ID, 
           SUM(VS.TOTAL_VIEWS) AS TV, 
           SUM(VS.TOTAL_UNIQUE_VIEWS) AS TUV 
    FROM CTE 
    JOIN VIEW_STATS AS VS 
    ON VS.CHALLENGE_ID = CTE.CHALLENGE_ID 
    GROUP BY CTE.CONTEST_ID
)

SELECT C.CONTEST_ID, C.HACKER_ID, C.NAME, 
       CTE2.TS, CTE2.TAS, CTE3.TV, CTE3.TUV 
FROM CONTESTS AS C 
JOIN CTE2 
ON C.CONTEST_ID = CTE2.CONTEST_ID 
JOIN CTE3 
ON C.CONTEST_ID = CTE3.CONTEST_ID 
WHERE CTE2.TS != 0 
AND CTE2.TAS != 0 
AND CTE3.TV != 0 
AND CTE3.TUV != 0 
ORDER BY C.CONTEST_ID;
