SELECT W.ID, WP.AGE, W.COINS_NEEDED, W.POWER
FROM WANDS AS W
INNER JOIN WANDS_PROPERTY AS WP
ON W.CODE = WP.CODE
WHERE WP.IS_EVIL = 0
AND W.COINS_NEEDED = (
    SELECT MIN(W2.COINS_NEEDED)
    FROM WANDS AS W2
    INNER JOIN WANDS_PROPERTY AS WP2
    ON W2.CODE = WP2.CODE
    WHERE WP2.AGE = WP.AGE 
    AND W2.POWER = W.POWER
    AND WP2.IS_EVIL = 0
)
ORDER BY W.POWER DESC, WP.AGE DESC;
