WITH NEWTABLE AS (
    SELECT CI.NAME AS CITY_NAME, SUM(CI.POPULATION) AS SUM_POP 
    FROM CITY AS CI
    INNER JOIN COUNTRY AS CO
    ON CI.COUNTRYCODE = CO.CODE
    WHERE CO.CONTINENT = 'Asia'
    GROUP BY CI.NAME
)

SELECT SUM(SUM_POP)
FROM NEWTABLE;
