SELECT 
    CASE
        WHEN G.GRADE > 7 THEN S.NAME
        ELSE NULL
    END,
    G.GRADE AS VGRADE,
    S.MARKS AS NEW_MARK
FROM STUDENTS AS S
INNER JOIN GRADES AS G
ON S.MARKS BETWEEN G.MIN_MARK AND G.MAX_MARK
ORDER BY G.GRADE DESC,
    CASE
        WHEN G.GRADE > 7 THEN S.NAME 
        ELSE NULL
    END ASC,
    CASE
        WHEN G.GRADE <= 7 THEN S.MARKS
        ELSE NULL
    END ASC ;
