SELECT H.HACKER_ID, H.NAME
FROM HACKERS AS H
INNER JOIN SUBMISSIONS AS S
ON H.HACKER_ID = S.HACKER_ID
LEFT JOIN CHALLENGES AS C
ON S.CHALLENGE_ID = C.CHALLENGE_ID
INNER JOIN DIFFICULTY AS D
ON C.DIFFICULTY_LEVEL = D.DIFFICULTY_LEVEL
WHERE S.SCORE = D.SCORE
GROUP BY H.HACKER_ID, H.NAME
HAVING COUNT(*) > 1
ORDER BY COUNT(H.HACKER_ID) DESC, H.HACKER_ID ASC;
